apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersystem-deployment
  namespace: seulki
spec:
  replicas: 2 
  selector: 
    matchLabels:
        app: ordersystem
  template: # template : pod 정의
    metadata:
      labels: 
        app: ordersystem
    spec:
      containers:
        - name: ordersystem
        # aws의 ecr 주소 사용
          image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/seulki-ordersystem:latest
          ports: 
          - containerPort: 8080
          resources:
          # 최대 할당가능량
            limits:
              cpu: "1"
              memory: "500Mi"
          # 최소 할당가능량
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                key: REDIS_HOST
                name: seulki-app-secrets
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: seulki-app-secrets
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
                name: seulki-app-secrets
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: seulki-app-secrets
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET
                name: seulki-app-secrets
          - name: JWT_SECRET_RT
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET_RT
                name: seulki-app-secrets
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY
                name: seulki-app-secrets
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_KEY
                name: seulki-app-secrets
          # 무중단 배포를 위한 컨테이너 health check
          readinessProbe:
            httpGet:
              path: /product/list
              port: 8080
            # 컨테이너 시작 후 지연시간 설정
            initialDelaySeconds: 10 # 10초 후에 헬스체크 시작
            # 확인반복주기
            periodSeconds: 10 # 10초마다 헬스체크
            # 요청 타임아웃 설정
            timeoutSeconds: 1 # 1초 이내에 안오면 실패처리
            # 성공 인식 횟수 설정
            successThreshold: 1
            # 연속 실패 횟수 : 연속적으로 5번을 실패하면 건강하지 않은 상태로 판단하여 기존서버 종료시키지 않음
            failureThreshold: 5

            
                