apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: seulki
spec:
  replicas: 2 # pod를 2개를 유지하겠다 선언
  # 아래 요소는 replicatset이 관리할 파드를 선택하기 위한 이름
  # template.metadata.labels의 이름과 일치해야함
  selector: 
    matchLabels:
        app: my-nginx
  template: # template : pod 정의
    # labels.app 부분은 service의 selector 부분과 일치해야 하고,
    # matchLabels와도 일치해야 함 (3개가 equal관계 유지해야 함)
    metadata:
      labels: 
        app: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports: 
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: seulki
spec: 
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30602
  selector:
    app: my-nginx # Pod의 labels.app은 service의 selector.app의 이름과 싱크가 맞아야한다.