apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: seulki
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: seulki
  labels: 
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: seulki
spec: 
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30602
  selector:
    app: my-nginx # Pod의 labels.app은 service의 selector.app의 이름과 싱크가 맞아야한다.