# 2. ClusterIssuer 생성
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: seulki
spec:
  acme:
  # 인증서 서버 주소. 해당 서버의 리소스를 통해 인증서 발행
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wisdom0405@kakao.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
# 3. Certificate 생성
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisdom0405-com-tls # 이름아무거나 가능
  namespace: seulki
spec:
  secretName: wisdom0405-com-tls
  duration: 2160h #90일
  renewBefore: 360h #15일 전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.wisdom0405.shop #도메인명
  dnsNames:
  - server.wisdom0405.shop #도메인명